name: Scan with Detekt

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '27 4 * * 1'
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.15.0

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Detekt download URL
        id: detekt_info
        run: |
          DETEKT_DOWNLOAD_URL=$(gh api graphql --field tagName=$DETEKT_RELEASE_TAG --raw-field query='
            query getReleaseAssetDownloadUrl($tagName: String!) {
              repository(name: "detekt", owner: "detekt") {
                release(tagName: $tagName) {
                  releaseAssets(name: "detekt", first: 1) {
                    nodes {
                      downloadUrl
                    }
                  }
                }
              }
            }
          ' | jq --raw-output '.data.repository.release.releaseAssets.nodes[0].downloadUrl')
          echo "::set-output name=download_url::$DETEKT_DOWNLOAD_URL"

      - name: Setup Detekt
        run: |
          dest=$(mktemp -d)
          curl --request GET \
            --url ${{ steps.detekt_info.outputs.download_url }} \
            --silent \
            --location \
            --output $dest/detekt
          chmod a+x $dest/detekt
          echo $dest >> $GITHUB_PATH

      - name: Run Detekt
        continue-on-error: true
        run: |
          ${{ env.DETEKT_RELEASE_TAG }}/detekt --input ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt.sarif.json

      - name: Make artifact location URIs relative
        continue-on-error: true
        run: |
          echo "$(
            jq \
              --arg github_workspace ${{ github.workspace }} \
              '. | ( .runs[].results[].locations[].physicalLocation.artifactLocation.uri |= if test($github_workspace) then .[($github_workspace | length | . + 1):] else . end )' \
              ${{ github.workspace }}/detekt.sarif.json
          )" >${{ github.workspace }}/detekt.sarif.json

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/detekt.sarif.json
          checkout_path: ${{ github.workspace }}
          token: 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
          matrix: null
          wait-for-processing: true
